services:
    core.utils.encryption:
        class: Zend\Crypt\BlockCipher
        factory: 'Zend\Crypt\BlockCipher::factory'
        arguments:
            - "mcrypt"
        calls:
            - [ "setKey", [ "%encryption_key%" ] ]
#            - [ "setSalt", [ "%encryption_salt%" ] ] # TODO Do we still need to set the salt here?

    core.security.provider.user:
        class: CoreBundle\Security\Core\User\HWIOAuthUserProvider\UserProvider
        arguments:
            - '@fos_user.user_manager'
            -
                facebook: facebookId
                twitter: twitterId
