services:
    core.utils.encryption:
        class: Zend\Crypt\BlockCipher
        factory: 'Zend\Crypt\BlockCipher::factory'
        arguments:
            - "mcrypt"
        calls:
            - [ "setKey", [ "%encryption_key%" ] ]

    core.security.provider.user:
        class: CoreBundle\Security\Core\User\HWIOAuthUserProvider\UserProvider
        arguments:
            - "@fos_user.user_manager"
            -
                facebook: facebookId
                twitter: twitterId

    core.tactician.middleware.stopwatch:
        class: CoreBundle\Tactician\Middleware\StopwatchMiddleware
        arguments:
            - "@debug.stopwatch"

    core.service.smashgg:
        class: CoreBundle\Service\Smashgg\Smashgg
