parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.6'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        url: 'mysql://%env(resolve:DB_USERNAME)%:%env(resolve:DB_PASSWORD)%@%env(resolve:DB_HOST)%:3306/%env(resolve:DB_NAME)%'
        types:
            encrypted: App\Doctrine\DBAL\Types\EncryptedType
            hashed: App\Doctrine\DBAL\Types\HashedType
        mapping_types:
            encrypted: encrypted
            hashed: hashed
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
