jms_serializer:
    default_context:
        serialization:
            serialize_null: true
    property_naming:
        id: JMS\Serializer\Naming\SerializedNameAnnotationStrategy

services:
    JMS\Serializer\Naming\SerializedNameAnnotationStrategy:
        arguments:
            - '@jms_serializer.identical_property_naming_strategy'
