nelmio_api_doc:
    documentation:
        info:
            title: SmashArchive API
            description: The REST(ish) API of SmashArchive
            version: 0.2.1
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc) # Accepts routes under /api except /api/doc
