services:
    admin.character:
        class: AdminBundle\Admin\CharacterAdmin
        arguments: [~, CoreBundle\Entity\Character, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Characters }

    admin.country:
        class: AdminBundle\Admin\CountryAdmin
        arguments: [~, CoreBundle\Entity\Country, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Countries }

    admin.event:
        class: AdminBundle\Admin\EventAdmin
        arguments: [~, CoreBundle\Entity\Event, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Event }

    admin.player:
        class: AdminBundle\Admin\PlayerAdmin
        arguments: [~, CoreBundle\Entity\Player, AdminBundle:Player ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Players, pager_type: simple }
        calls:
          - ['setCacheManager', ['@core.service.cache.manager']]

    admin.series:
        class: AdminBundle\Admin\SeriesAdmin
        arguments: [~, CoreBundle\Entity\Series, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Series }

    admin.tournament:
        class: AdminBundle\Admin\TournamentAdmin
        arguments: [~, CoreBundle\Entity\Tournament, AdminBundle:Tournament ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Tournaments, pager_type: simple }
        calls:
          - ['setCache', ['@cache.provider.filesystem']]

    admin.job:
        class: AdminBundle\Admin\JobAdmin
        arguments: [~, CoreBundle\Entity\Job, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Jobs }

    admin.user:
        class: AdminBundle\Admin\UserAdmin
        arguments: [~, CoreBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Users }

    admin.form.tournament.import:
        class: AdminBundle\Form\ImportTournamentType
        arguments: ['@core.service.smashgg']
        tags:
            - { name: form.type }