services:
    bus.handler.player.overview:
        class: Domain\Handler\Player\OverviewHandler
        arguments:
            - '@knp_paginator'
        tags:
            - { name: "tactician.handler", command: Domain\Command\Player\OverviewCommand }
        calls:
            - ['setEntityManager', ['@doctrine.orm.entity_manager']]

    bus.handler.player.details:
        class: Domain\Handler\Player\DetailsHandler
        tags:
            - { name: "tactician.handler", command: Domain\Command\Player\DetailsCommand }
        calls:
            - ['setEntityManager', ['@doctrine.orm.entity_manager']]

    bus.handler.player.results:
        class: Domain\Handler\Player\ResultsHandler
        tags:
            - { name: "tactician.handler", command: Domain\Command\Player\ResultsCommand }
        calls:
            - ['setEntityManager', ['@doctrine.orm.entity_manager']]

    bus.handler.player.head_to_head:
        class: Domain\Handler\Player\HeadToHeadHandler
        tags:
            - { name: "tactician.handler", command: Domain\Command\Player\HeadToHeadCommand }
        calls:
            - ['setEntityManager', ['@doctrine.orm.entity_manager']]
