imports:
    - { resource: handlers.yml }

services:
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ "setAnnotationReader", [ "@annotation_reader" ] ]
