imports:
    - { resource: handlers.yml }

services:
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ "setAnnotationReader", [ "@annotation_reader" ] ]

    monolog.formatter.json:
        class: CoreBundle\Monolog\Formatter\JsonFormatter

    monolog.processor.sentry:
        class: CoreBundle\Monolog\Processor\SentryProcessor
        arguments:
            - "%kernel.environment%"
        tags:
            - { name: monolog.processor, method: processRecord, handler: sentry }
